# Generated by Django 6.1 on 2026-08-31 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='emoji',
        ),
    ]
