# Generated by Django 6.1 on 2026-08-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_remove_word_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='has_photo',
            field=models.BooleanField(default=True, help_text='Desmarque para palavras abstratas (verbos, preposições, conceitos) onde uma foto não ajuda — o modo Foto nem aparece pro aluno nesses casos.', verbose_name='tem foto que faz sentido'),
        ),
    ]
