# Generated by Django 6.1 on 2026-08-31 21:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_word_has_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='known',
        ),
        migrations.AddField(
            model_name='progress',
            name='last_wrong_answer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='progress',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='next_review',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='word',
            name='photo_page',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='página da foto na Wikipedia'),
        ),
        migrations.AddField(
            model_name='word',
            name='photo_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='foto (capa da Wikipedia)'),
        ),
    ]
