# Generated by Django 6.1 on 2026-09-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_remove_progress_known_progress_last_wrong_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='ai_feedback_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='photo_credit',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='crédito da foto'),
        ),
        migrations.AlterField(
            model_name='word',
            name='photo_page',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='página de origem da foto'),
        ),
        migrations.AlterField(
            model_name='word',
            name='photo_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='foto'),
        ),
    ]
