# Generated by Django 6.1 on 2026-09-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_profile_ai_feedback_profile_ai_feedback_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='photo_variants',
            field=models.JSONField(blank=True, default=list, verbose_name='outras fotos disponíveis'),
        ),
        migrations.AlterField(
            model_name='word',
            name='photo_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='foto (capa)'),
        ),
    ]
