# Generated by Django 6.1 on 2026-09-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_word_photo_variants_alter_word_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
