# Generated by Django 6.1 on 2026-09-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_profile_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='consecutive_errors',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='is_leech',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
