# Generated by Django 6.1 on 2026-09-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_progress_consecutive_errors_progress_is_leech'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='last_wrong_lang',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
