# Generated by Django 6.1 on 2026-09-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0009_progress_last_wrong_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='frequency_band',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='1=top-500, 2=top-1500, 3=top-3000, 0=fora', verbose_name='banda de frequência'),
        ),
    ]
