# Generated by Django 6.1 on 2026-09-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0011_studysession'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coach_enabled',
            field=models.BooleanField(default=False, help_text='Se ligado, envia resumo de erros/rodadas pra Gemini/Groq gerar feedback. Padrão desligado (privacy by default).', verbose_name='coach de IA ligado'),
        ),
    ]
